language: node_js
node_js:
    - "8"

addons:
  chrome: stable
  
cache:
    directories:
    - "node_modules"
    
before_install:
    - npm install -g karma-cli
    - export CHROME_BIN=chromium-browser
    - "npm install mocha -g"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    
script:
    - npm run test
    