language: node_js
node_js:
    - "8"

before_install:
    - "npm install mocha -g"
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
 
cache:
    directories:
    - "node_modules"
    
script:
    - npm test
    - npm run build